action_id: trunk-upgrade-available
date: 2023-03-24 13:50:43
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: line 1: trunk: command not found\n"
timestamp: 1679665843
full_timestamp:
  nanos: 759720000
  seconds: 1679665843
trunk_version: 1.6.1
